export const COM_SHOW_SIDE_BAR = 'COM_SHOW_SIDE_BAR'  //侧边栏
export const COM_SAVE_SEARCH_HISTORY = 'COM_SAVE_SEARCH_HISTORY' //保存搜索历史
export const COM_DELETE_SEARCH_HISTOEY = 'COM_DELETE_SEARCH_HISTOEY' //删除历史记录
export const COM_DELETE_ALL_SEARCH_HISTOEY = 'COM_DELETE_ALL_SEARCH_HISTOEY'