export const INPUT_BLUR = "header/input_blur"
export const INPUT_FOCUES = "header/input_focus"
export const CHANGE_LIST = "header/change_list"
export const MOUSE_ENTER = "header/mouse_enter"
export const MOUSE_LEAVE = "header/mouse_leave"
export const CHANGE_PAGE = "header/change_page"